const projects = [
  {
    id: "01",
    title: "When Forests Become Frontiers",
    italicWord: "Frontiers",
    tags: ["Research", "Environmental Justice", "Borneo", "Public Empowerment"],
    desc: "Six-part drawing series examining meranti extraction in West Borneo and its impact on Dayak communities.",
    long: "In Sabar Bubu, West Borneo, the forest’s rhythms are increasingly shaped by chainsaws and transport trucks as global demand for exotic hardwoods such as mahogany, teak, and meranti drives intensified extractivism. Expanding state forestry concessions overlap with Indigenous customary territories, accelerating deforestation, degrading biodiversity, and generating persistent disputes over land and authority. Meranti, prized for its strength and durability, is harvested at rates that exceed the forest’s regenerative capacity. For Dayak communities, meranti is more than a commodity. It defines adat boundaries, supports spiritual practices, and embodies ecological memory. Its disappearance represents not only environmental loss but also cultural erosion, as anchors of collective life and belonging vanish with the canopy. Drawing on Anna Tsing’s concept of friction as unequal and unstable encounters, this research frames these conflicts as sites where global markets and state forestry regimes unsettle Indigenous worlds and reshape the politics of land, legality, and identity.",
    year: "2025",
    medium: "Drawing / Research",
    image: "Image/Project_1/07_DH_Proj1.png",
    video: "https://www.youtube.com/embed/kDRsn2oVqQE?autoplay=1&mute=1",
    location: "West Borneo",
    status: "Completed",
    color: "linear-gradient(135deg, #3d4e1f 0%, #2c3816 100%)",
    images: [
      { src: "Image/Project_1/01_DH_Proj1.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_1/02_DH_Proj1.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: true,
        layout: "single"
      },
      // {
      //   layout: "duo",    
      //   srcs: [
      //     "Image/Project_1/03_DH_Proj1.png",
      //     "Image/Project_1/04_DH_Proj1.png",
      //   ],
      //   title: "Dayak Cosmology and the Meaning of Nature",
      //   text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      // },
      // { src: "Image/Project_1/05_DH_Proj1.png", 
      //   title: "Illicit Process During Extraction",
      //   text: "Extraction in West Borneo brings social and material devastation beyond forest loss. Dayak families face eviction, burned homes, destroyed tools, and illegal logging practices that evade detection. As exploitation deepens, communities turn to prayer and ritual, drawing spiritual resilience to endure and resist forces greater than their political and economic power.",  
      //   reverse: false,
      //   layout: "single"
      // },
            {
        layout: "full",
        src: "Image/Project_1/03_DH_Proj1.png", 
        title: "Dayak Cosmology and the Meaning of Nature",
        text: "Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation.",
      },
            { src: "Image/Project_1/04_DH_Proj1.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_1/05_DH_Proj1.png", 
        title: "Illicit Process During Extraction",
        text: "Extraction in West Borneo brings social and material devastation beyond forest loss. Dayak families face eviction, burned homes, destroyed tools, and illegal logging practices that evade detection. As exploitation deepens, communities turn to prayer and ritual, drawing spiritual resilience to endure and resist forces greater than their political and economic power.",
      },
      { src: "Image/Project_1/06_DH_Proj1.png", 
        title: "Vicious Cycle",
        text: "Forest conflict in West Borneo exposes a political and economic cycle that weakens Indigenous land rights. Overlapping laws, poor enforcement, and corruption enable state institutions and corporations to benefit from extraction. Through elite networks and permits, concessions expand despite objections, leaving Dayak communities with rights recognized legally but undermined in practice." ,  
        reverse: false,
        layout: "single"
      },

    ],

  },
  {
    id: "02",
    title: "South Bronx Pedestrian Atlas",
    italicWord: "Atlas",
    tags: ["Web Mapping", "Mapbox GL JS", "C#", "JavaScript","Digital Commisioning"],
    desc: "Interactive web application visualizing pedestrian density, traffic flows, and PLOS across the South Bronx.",
    long: "This proposal advances an integrated strategy to transform South Bronx streets into safer, more inclusive, and community oriented public spaces by rebalancing movement and place. Although many corridors experience high pedestrian volumes, they continue to function primarily as vehicular thoroughfares, creating unsafe and stressful walking environments. Through traffic counts, pedestrian flow mapping, and density analysis, the strategy identifies redundant travel lanes and underutilized right of way that can be reallocated to widen sidewalks, enhance crossings, and introduce flexible public space. Corridors with excess vehicular capacity are prioritized for activation through the Open Streets program, incorporating modular and movable furniture to accommodate daily activities, local markets, and community gatherings. Mobility systems are reorganized through time based freight management, designated loading zones, and integrated bicycle, micromobility, and transit infrastructure. Together, these interventions reduce conflicts, improve circulation efficiency, and support a more equitable and people centered street environment.",
    year: "2025",
    medium: "Web Application",
    image: "Image/Project_2/01_DH_Proj2.png",
    prototype: {
      url: "https://danieljharianto.github.io/SBX_WebMap/",
      label: "Map Platform"  
    },
    // video: "https://www.youtube.com/embed/kDRsn2oVqQE",
    location: "South Bronx, NY",
    status: "Completed",
    color: "linear-gradient(135deg, #4a5e28 0%, #3d4e1f 100%)",
    images: [
      { src: "Image/Project_2/02_DH_Proj2.png", 
        title: "Mobility Publlic Engagement",
        text: "Grounded in pedestrian and traffic analysis and informed by community engagement with South Bronx Unite, the project balances lived experience with data-driven design. In partnership with NYC EDC, it reallocates excess roadway into wider sidewalks, flexible Open Streets, and modular public furniture, while coordinating freight and mobility to reduce conflicts.",   
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_2/05_DH_Proj2.png", 
        title: "From Analysis to Initiative",
        text: "This project translates performative urban analysis into tangible public action by using data on pedestrian movement, street capacity, and everyday use to directly inform community-led interventions. Rather than remaining abstract, analytical findings are tested on the ground through the Open Streets program, where excess roadway is temporarily reclaimed and activated as part of public community festivals." ,  
        reverse: true,
        layout: "single"
      },
      { src: "Image/Project_2/03_DH_Proj2.png", 
        title: "Open Data and Mobility Knowledge",
        text: "The digital platform uses intuitive maps, visuals, and interactive tools to help residents and decision-makers explore street conditions, movement patterns, and opportunities. By simplifying complex data, it makes information clear, transparent, and actionable for public engagement.",   
        reverse: false,
        layout: "single"
      },
      // { src: "Image/Project_2/04_DH_Proj2.png", 
      //   title: "Demand History of Exotic Wood – Meranti",
      //   text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
      //   reverse: true,
      //   layout: "single"
      // },
      {
        layout: "full",
        src: "Image/Project_2/04_DH_Proj2.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      { src: "Image/Project_2/06_DH_Proj2.png", 
        title: "Digital Toolkit as Resource",
        text: "Selected interventions target streets identified through analysis of pedestrian demand, traffic, and capacity. By focusing on key corridors rather than broad citywide changes, the toolkit translates data directly into street-level design actions.",   
        reverse: true,
        layout: "single"
      },
      // { src: "Image/Project_2/07_DH_Proj2.png", 
      //   title: "Demand History of Exotic Wood – Meranti",
      //   text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
      //   reverse: true,
      //   layout: "single"
      // },
            {
        layout: "full",
        src: "Image/Project_2/07_DH_Proj2.png",
        title: "Public Realm Improvement",
        text: ["Priority streets are selected where high pedestrian activity overlaps with underutilized roadway space, enabling the reallocation of lanes into wider sidewalks, safer crossings, and flexible public areas. In doing so, the strategy not only improves walking conditions but also strengthens the role of streets as social and economic spaces that support local businesses and community activities."]
      },
      {
        layout: "full",
        src: "Image/Project_2/10_DH_Proj2.gif",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      {
        layout: "full",
        src: "Image/Project_2/09_DH_Proj2.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
    ],
  },
  {
    id: "03",
    title: "OrangoPlan — Grasshopper Plugin",
    italicWord: "Plugin",
    tags: ["C#", "Python","Grasshopper SDK","Digital Commisioning"],
    desc: "Grasshopper plug enabling real-time urban design and planning prototyping.",
    long: "OrangoPlan provides parametric tools to model, analyze, and visualize complex urban design workflows. It enables designers and planners to create adaptive street networks, land-use layouts, building massing, public space configurations, and infrastructure simulations.",
    year: "2024 - Ongoing",
    medium: "Software / Plugin",
    image: "Image/Project_3/01_DH_Proj3.png",
    prototype: {
      url: "https://danieljharianto.github.io/OrangoPlanDocs.github.io/",
      label: "Plugin Documentation"  
    },
    video: "https://www.youtube.com/embed/K9SeA-3_E0w?autoplay=1&mute=1",
    location: "MIT SA+P",
    status: "Ongoing",
    color: "radial-gradient(ellipse at top left, #566830 0%, #2c3816 100%)",
    images: [
      { src: "Image/Project_3/02_DH_Proj3.png", 
        title: "Digital Toolkit for Urban Design",
        text: "The plugin helps make better decisions by combining spreadsheets, planning rules, and measurable factors to improve city design, livability, and sustainability. This tool is ideal for master planning, zoning studies, and rapid prototyping of urban-scale interventions.",   
        reverse: false,
        layout: "single"
      },
      // { src: "Image/Project_1/02_DH_4.228.png", 
      //   title: "Disputed Extraction Site",
      //   text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
      //   reverse: true,
      //   layout: "single"
      // },
          {
        layout: "full",
        src: "Image/Project_3/03_DH_Proj3.png",
        title: "Plugin Capabilities",
        text: ["It also bridges the gap between urban analysis and design implementation. Analytical inputs such as density limits, circulation patterns, land-use allocation, and regulatory constraints can be directly translated into spatial configurations, allowing designers to test multiple development scenarios in real time. By integrating evaluation and design within a single workflow, the tool supports efficient iteration, helping planners quickly compare alternatives, assess performance, and refine proposals that respond to both planning regulations and urban design objectives."],
      },
          {
        layout: "full",
        src: "Image/Project_3/04_DH_Proj3.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
                {
        layout: "full",
        src: "Image/Project_3/05_DH_Proj3.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },



    ],
  },
  {
    id: "04",
    title: "Smoked County Relish",
    italicWord: "Relish",
    tags: ["Thesis", "C#","Java Script","Python","Building Science","Discrete Math"],
    desc: "Rethinking coastal culture to revoke poverty and technological disjunction in Indonesia",
    long: "Indonesia, as a country consisting of islands, holds an affinity for coastal cultures. Evolve within absolute time; the indigenous support their lives by gaining the source and preserving it with various methods. Semarang City, located on northern Java Island, is famous for its smoked fish preservation. As they believe the technique is sea frontliners inheritance, they are stigmatized as second-class people. The design effort seeks appropriateness and reuse of heritage buildings to secure the perimeter and encourage community resilience. In tourism attraction strategy, they must race during environmental degradation.",
    year: "2021",
    medium: "Computational Design",
    prototype: {
      url: "https://www.designboom.com/architecture/daniel-jansen-harianto-the-smoked-county-relish-thesis-project-indonesia-09-09-2022/",
      label: "Published Media"  
    },
    image: "Image/Project_4/01_DH_Proj4.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns?autoplay=1&mute=1",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_4/11_DH_Proj4.png", 
        title: "Historical Evidence as Catalyst",
        text: "Bandarharjo’s coastal location along the Semarang River has long supported a strong fish-smoking tradition that sustains local livelihoods and drives a circular economy. Using simple, natural tools—coconut fiber fuel, bamboo skewers, and wooden fans, the community prepares smoked fish that is later cooked into local dishes such as yellow broth fish soup and stir-fry.",   
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_4/12_DH_Proj4.png", 
        title: "Annihilate Placelessness",
        text: "Scattered along the Semarang River, traditional fish-smoking houses reflect cultural values rooted in the Semarang Old Town. To preserve this heritage amid land subsidence and tidal flooding, an abandoned colonial warehouse is repurposed into a fish-smoking complex. This adaptive reuse honors local identity, activates the riverfront, and provides a resilient space that sustains both the tradition and the community’s pride.",   
        reverse: true,
        layout: "single"
      },
      { src: "Image/Project_4/03_DH_Proj4.png", 
        title: "Mapping Livelihood and Risk",
        text: "Through mapping, the fish-smoking houses are located along the Semarang River corridor, revealing their proximity to tidal flooding zones, land subsidence areas, and colonial-era infrastructures connected to Semarang Old Town. " ,  
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_4/09_DH_Proj4.png", 
        title: "Algorithm Approach",
        text: "The fish-smoking compound design empowers residents by optimizing neighborhood-sourced materials, processed computationally using the marching cubes algorithm. Materials are sorted, matched to building components, and quantified, improving efficiency while accurately estimating construction costs." ,  
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_4/08_DH_Proj4.gif",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      { src: "Image/Project_4/06_DH_Proj4.png", 
        title: "Retrofitting Commercial Hub",
        text: "The building’s main façade serves as a gateway, emphasizing its role as a symbolic and functional entry point to the fish smoking compound, bridging into the heart of the heritage and community. The concept involves revitalizing the community’s role as a central point of commerce. It also ensures destination needs while maintaining its historical significance.",   
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_4/10_DH_Proj4.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      // {
      // layout: "duo",    
      //   srcs: [
      //     "Image/Project_4/05_DH_Proj4.png",
      //     "Image/Project_4/04_DH_Proj4.png",
      //   ],
      //   title: "Dayak Cosmology and the Meaning of Nature",
      //   text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      // },
      { src: "Image/Project_4/07_DH_Proj4.png", 
        title: "Material Stratification",
        text: "Structural frame from reclaimed hardwood; secondary infill panels from bamboo weaving; roofing from reused corrugated metal elevated for ventilation. The tectonic expression remains honest—joints are visible, connections bolted rather than concealed—celebrating the afterlife of materials." ,  
        reverse: false,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_4/01_DH_Proj4.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },

    ],
  },
  {
    id: "05",
    title: "Jakarta TOD-POD Implementation",
    italicWord: "Implementation",
    tags: ["Research",,"C#", "Python", "Urban Mobility", "Public Empowerment"],
    desc: "Creating a TOD-POD template to better shape urban mobility within the Jakarta Metropolitan Area.",
    long: "The Jakarta metropolitan area (Jabodetabek) consists of Jakarta, Bogor, Depok, Tangerang, and Bekasi, covering over 6,438 sq km, and it is considered the second largest metropolitan area in the world after the Tokyo metropolitan area in Japan (14,034 sq km). The metropolitan area is home to a population of 40 million people in 2022.There has been relatively little focus on the ‘implementation’ of strategic imperatives, with most urban development and transit initiatives emerging through either reactive or speculative means. Therefore, the city’s planning administration needs to strengthen its understanding and knowledge in planning Transit-Oriented Development (TOD) and Pedestrian-Oriented Design (POD).",
    year: "2023",
    medium: "Computational Design",
    image: "Image/Project_5/01_DH_Proj5.png",
    location: "Soegijapranata Catholic University",
    location: "Jakarta, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_5/07_DH_Proj5.png", 
        title: "Public Driven Engagement",
        text: "This activity included semi-structured interviews with the Head of the Neighborhood to explore economic drivers that could create opportunities for low-income residents and strengthen their adaptive capacity around the TOD-POD. In collaboration with DKI Jakarta agencies, the TOD-POD is planned as a neighborhood center for East Jakarta, with its role in the activity hierarchy shaping future real estate development and positioning.",   
        reverse: false,
        layout: "single"
      },
      // { src: "Image/Project_5/03_DH_Proj5.png", 
      //   title: "Disputed Extraction Site",
      //   text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
      //   reverse: true,
      //   layout: "single"
      // },
            { src: "Image/Project_5/08_DH_Proj5.png", 
        title: "User Experience Initiative",
        text: "To facilitate seamless footpath connectivity between public transport modes and public facilities such as markets, schools, parks, and others, the TOD-POD must provide a continuous guiding block path and a standardized ramp." ,  
        reverse: true,
        layout: "single"
      },
                  {
        layout: "full",
        src: "Image/Project_5/03_DH_Proj5.png",
        title: "Masterplan Strategy",
        text: ["Located in East Jakarta (Klender), the pilot study covers an 800 m radius around Klender (Lama) Station, with a 400 m core focus area for development. The goal is to create the densest, mixed-use zone that supports walking and cycling, with select plots planned for higher density to meet future demand."],
      },

            {
        layout: "full",
        src: "Image/Project_5/05_DH_Proj5.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
            {
        layout: "full",
        src: "Image/Project_5/06_DH_Proj5.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      {
        layout: "full",
        src: "Image/Project_5/02_DH_Proj5.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },

    ],
  },
  {
    id: "07",
    title: "Indonesia New Capital City Urban Design Guidelines",
    italicWord: "Guidelines",
    tags: ["Research", "C#", "Python", "Planning Modelling"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_7/07_DH_Proj7.png",
    // video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Nusantara, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_7/03_DH_Proj7.png", 
        title: "Urban Typologies",
        text: "The design of the development focuses on undulating surfaces to cover sensitive wetland features and existing fault lines. It connects buildings to the ground level through pedestrian pathways and thru-block designs or elevated pathways on higher ground, ensuring efficiency and permeability of the plots within the development." ,  
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_7/09_DH_Proj7.png", 
        title: "Multi-Layered Circulation Hierarchy",
        text: "The analysis distinguishes between pedestrian corridors, micromobility lanes, public transit routes, and service access. Primary boulevards concentrate civic and governmental functions, encouraging walkability within a 5–10 minute radius. Secondary paths connect residential clusters to mixed-use nodes, reducing dependency on private vehicles.",   
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_7/08_DH_Proj7.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
                        {
        layout: "full",
        src: "Image/Project_7/02_DH_Proj7.gif",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      // {
      // layout: "duo",    
      //   srcs: [
      //     "Image/Project_4/05_DH_Proj4.png",
      //     "Image/Project_4/04_DH_Proj4.png",
      //   ],
      //   title: "Dayak Cosmology and the Meaning of Nature",
      //   text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      // },
      { src: "Image/Project_7/05_DH_Proj7.png", 
        title: "Plot Densification Guides",
        text: "As one of the detailed precincts, the education area is the heart of Sub Planning 1B, with the main function of Edu-town focusing on an integrated education and research complex supported by low- to high-density residential, amenities, and commercials.The computational approach creates development parameters that consider current design preferences and natural conditions. " ,  
        reverse: false,
        layout: "single"
      },
                  {
        layout: "full",
        src: "Image/Project_7/04_DH_Proj7.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      { src: "Image/Project_7/10_DH_Proj7.png", 
        title: "Tailored Design Recommendations",
        text: "Each designed plot parameter includes total developable area, FAR, BCR, and maximum tower inside the plot. Based on this self-created development parameter, it can be summarized to gain more insights about the Edu-town area, referring to its forecast density, occupancy, and employment numbers that correspond to further implementations.",   
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_7/06_DH_Proj7.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      {
        layout: "full",
        src: "Image/Project_7/01_DH_Proj7.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },


    ],
  },
  {
    id: "06",
    title: "Reclaiming Necessity Coastal Demak",
    italicWord: "Coastal Demak",
    tags: ["Research", "C#","Java Script","Python","Building Science","Discrete Math"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "Coastal people’s habit of hoarding abandoned materials forms the basis for the dignified transformation of immaterial debris into supportive habitation. Rather than being a source of negative values, it could potentially serve as an alternative means of surviving under the natural degradation caused by sea level rise. The community of 285 houses in Bedono, Coastal Demak, Central Java, is the target of this project, which aims to introduce a fresh approach to construction by repurposing leftover materials for more advantageous investments. In addition to the economic challenges, purchasing new materials for house repairs is no longer feasible due to factors such as inflation and declining occupancy, which could potentially “suffocate” the community.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_6/01_DH_Proj6.png",
    // video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_6/02_DH_Proj6.png", 
        title: "Research on the Building Typologies",
        text: "Bedono, Coastal Demak, Central Java, consists of various housing typologies and sized developments that have been established throughout the years. The data collection was recorded based on the inhabitants’ interviews about how long they had settled in the place.",   
        reverse: false,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_6/05_DH_Proj6.png",
      },
      { src: "Image/Project_6/09_DH_Proj6.png", 
        title: "Mitigation Plan and Execution",
        text: "Due to limited municipal census data and residents’ lack of insurance or financial support, the renovation scheme prioritized severely sunken houses, especially those submerged by more than one meter.",   
        reverse: true,
        layout: "single"
      },
      { src: "Image/Project_6/03_DH_Proj6.png", 
        title: "Focus Group Discussion",
        text: "Local government visited each damaged house in the focus area to assess and record settlement damage, with residents encouraged to report their own house conditions individually. After the mapping, the Head of the Hamlet convened a forum where family representatives shared ideas to improve housing and develop strategies to reduce the impacts of tidal floods." ,  
        reverse: false,
        layout: "single"
      },
      // { src: "Image/Project_6/06_DH_Proj6.png", 
      //   title: "Mock Up Construction",
      //   text: "Using salvaged materials from the surrounding area, a 28 sqm mock-up house was built to demonstrate repair methods, helping residents understand the process successfully.",   
      //   reverse: true,
      //   layout: "single"
      // },
       {
        layout: "full",
        src: "Image/Project_6/11_DH_Proj6.png",
        title: "Lower Income Housing Resilience",
        text: ["The three most common low-income housing typologies show varying flood resilience. The Overhang House survives up to 0.5 m, the Single Gable House up to 0.75 m, and the Concrete Slab House up to 1.25 m of water level rise. Elevating any of these structures by 0.5–1.25 m can significantly extend their survival threshold, offering a low-cost adaptive strategy against land subsidence and coastal flooding."],
      },
             {
        layout: "full",
        src: "Image/Project_6/12_DH_Proj6.png",
        title: "Higher IncomeHousing Resilience",
        text: ["The three 42 sqm typologies common among higher-income households show greater baseline resilience. Both the Multi Gable and Long House survive up to 0.5 m, while the Concrete Slab House performs significantly better at 1.75 m. Elevating by 1 m extends the first two to 2 m tolerance, and just 0.75 m of elevation pushes the concrete slab threshold to 2.25 m — well above projected flood scenarios."],
      },
      // {
      // layout: "duo",    
      //   srcs: [
      //     "Image/Project_6/08_DH_Proj6.png",
      //     "Image/Project_6/04_DH_Proj6.png",
      //   ],
      //   title: "Dayak Cosmology and the Meaning of Nature",
      //   text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      // },
    {
        layout: "full",
        src: "Image/Project_6/10_DH_Proj6.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      {
        layout: "full",
        src: "Image/Project_6/07_DH_Proj6.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
    ],
  },

  {
    id: "08",
    title: "Experimenting Gentle Density of  Tanah Abang TOD",
    italicWord: "TOD",
    tags: ["Research", "C#","Java Script","Python"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "Affordable housing near transit in Jakarta is increasingly scarce due to rapid urbanization and limited housing diversity. This research proposes gentle density, combining missing-middle housing with selective high-rise development to support inclusive growth. Focusing on the Tanah Abang TOD, a parametric workflow in Rhino and Grasshopper evaluates transit access and affordability to generate housing typologies. ",
    year: "2023",
    prototype: {
      url: "https://iopscience.iop.org/article/10.1088/1755-1315/1394/1/012022",
      label: "Published Paper"  
    },
    medium: "Computational Design",
    image: "Image/Project_8/01_DH_Proj8.png",
    location: "Jakarta, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_8/04_DH_Proj8.png", 
        title: "Missing Middle Housing",
        text: "Jakarta's rapid population growth and Generation Z's rising dominance in the housing market expose a critical gap in the city's residential landscape. Caught between dense informal kampung settlements and large-scale high-rise developments, Jakarta lacks the gradations of scale, affordability, and tenure that a growing and diverse population demands. Missing middle housing, encompassing mid-scale typologies such as townhouses, low-rise apartments, and courtyard housing, offers a vital bridge between these two extremes, providing adaptable and affordable options for younger residents entering the market. Addressing this gap is central to building more equitable and livable urban neighborhoods across Jakarta.",   
        reverse: false,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_8/03_DH_Proj8.png",
      },
      { src: "Image/Project_8/08_DH_Proj8.png", 
        title: "Housing Model Generation",
        text: "This model adopts an established method of generating building mass from a population density map (PDM), calculating building heights through empirical statistics on average area per person. By inputting forecasted population data into the building mass generation model, a three-dimensional master plan of the pilot project is produced, translating demographic projections directly into spatial form and enabling a data-driven approach to urban massing and density distribution.",   
        reverse: true,
        layout: "single"
      },
      // { src: "Image/Project_8/02_DH_Proj8.png", 
      //   title: "Computational Workflow - Ramhan Island  Planning",
      //   text: "Developed for Emaar, Ramhan Island centers on reconfiguring an existing reclaimed island into a high-end luxury destination. The computational workflow drives the redesign of the island's overall configuration — optimizing shoreline geometry, land use distribution, and built form placement to elevate the development's market positioning while delivering the spatial quality and exclusivity expected of a world-class luxury resort." ,  
      //   reverse: false,
      //   layout: "single"
      // },
      // { src: "Image/Project_6/06_DH_Proj6.png", 
      //   title: "Mock Up Construction",
      //   text: "Using salvaged materials from the surrounding area, a 28 sqm mock-up house was built to demonstrate repair methods, helping residents understand the process successfully.",   
      //   reverse: true,
      //   layout: "single"
      // },
      {
        layout: "full",
        src: "Image/Project_8/06_DH_Proj8.png",
        title: "Design Quality Improvement",
        text: ["Visibility analysis provides a means of geometrically describing the spaces and forms of a building as seen from a specific position. As such, it considers both fixed, building-related factors like space and form, as well as temporal, experiential ones like visibility and movement impact."],
      },
            {
        layout: "full",
        src: "Image/Project_8/07_DH_Proj8.png",
        title: "Massing Quality Improvement",
        text: ["Compactness is adopted as a core spatial metric to guide design quality across the plan. By measuring the shape property of all visible space relative to a circle, compactness identifies zones where an observer's spatial experience is continuous and consistent. Using the isoperimetric quotient at every point in the plan, areas scoring closer to 1 are prioritized in the design enhancement strategy, as they indicate more spatially coherent and perceptually comfortable environments for occupants and pedestrians alike."],
      },
            {
        layout: "full",
        src: "Image/Project_8/05_DH_Proj8.gif",
      //   title: "Design Improvement Plan",
      //   text: ["The design improvement strategy examines the balance between maintained units and saleable area, identifying opportunities to reorganize the residential program without sacrificing overall yield. Through iterative design testing, unit configurations are refined to maximize saleable keys while preserving the quality, exclusivity, and lifestyle amenities that define Ramhan Island's luxury offering."],
       },
       {
        layout: "full",
        src: "Image/Project_8/02_DH_Proj8.png",
        // title: "Mock Up Construction",
        // text: ["Using salvaged materials from the surrounding area, a 28 sqm mock-up house was built to demonstrate repair methods, helping residents understand the process successfully."],
      },

      { src: "Image/Project_8/09_DH_Proj8.png", 
        title: "Procedural Design Iteration",
        text: "The procedural design iteration synthesizes all parameters and goals into a unified generative workflow, where spatial metrics including visibility, compactness, and population density are continuously tested and refined across successive design cycles. Each iteration accommodates programmatic, environmental, and experiential targets simultaneously, allowing the design to evolve responsively toward a solution that balances density, liveability, and spatial quality. The result is a coherent built form that is not arrived at arbitrarily, but shaped and validated through a structured, data-informed design process.",   
        reverse: true,
        layout: "single"
      },
    ],
  },
  {
    id: "09",
    title: "Middle East Strategic",
    italicWord: "Strategic",
    tags: ["Research", "C#", "Python", "Planning Modelling"],
    desc: "Integrating spatial data, modeling, and scenario testing to guide design and market decisions",
    long: "Custom computational tools were developed to organize spatial, environmental, and market inputs into a flexible decision-making workflow, enabling rapid testing of design parameters, infrastructure alignments, and development scenarios tailored to Middle East contexts. Spatial modeling and scenario testing optimized land use, parcel configuration, and waterfront frontage to maximize sellable value while maintaining environmental performance and long-term identity, aligning design decisions with market demand and phasing strategies.",
    year: "2023",
    medium: "Computational Design",
    image: "Image/Project_9/01_DH_Proj9.png",
    location: "Abu Dhabi, UAE",
    status: "On Progress",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_9/09_DH_Proj9.png", 
        title: "Computational Workflow - Lulu Island  Planning",
        text: "Developed for Eagle Hills, Lulu Island is envisioned as a high-end resort destination defined by signature architecture and curated waterfront living. The computational workflow integrates parametric design tools to optimize site planning, unit distribution, and landscape performance ensuring the island's built form responds coherently to its coastal context while meeting the programmatic and aesthetic ambitions of a world-class luxury development.",   
        reverse: false,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_9/03_DH_Proj9.png",
      },
      { src: "Image/Project_9/04_DH_Proj9.png", 
        title: "Economical Improvement Plan and Execution",
        text: "The economical improvement strategy focuses on maximizing saleable area without compromising the quality of amenities or the resort experience. Through iterative computational analysis, the plan redistributes programmatic elements to reduce inefficiencies, consolidate shared infrastructure, and unlock additional developable area — all while preserving the signature character and consumer expectations central to Lulu Island's luxury positioning.",   
        reverse: true,
        layout: "single"
      },
      { src: "Image/Project_9/02_DH_Proj9.png", 
        title: "Computational Workflow - Ramhan Island  Planning",
        text: "Developed for Emaar, Ramhan Island centers on reconfiguring an existing reclaimed island into a high-end luxury destination. The computational workflow drives the redesign of the island's overall configuration — optimizing shoreline geometry, land use distribution, and built form placement to elevate the development's market positioning while delivering the spatial quality and exclusivity expected of a world-class luxury resort." ,  
        reverse: false,
        layout: "single"
      },
      // { src: "Image/Project_6/06_DH_Proj6.png", 
      //   title: "Mock Up Construction",
      //   text: "Using salvaged materials from the surrounding area, a 28 sqm mock-up house was built to demonstrate repair methods, helping residents understand the process successfully.",   
      //   reverse: true,
      //   layout: "single"
      // },
       {
        layout: "full",
        src: "Image/Project_9/06_DH_Proj9.png",
        // title: "Mock Up Construction",
        // text: ["Using salvaged materials from the surrounding area, a 28 sqm mock-up house was built to demonstrate repair methods, helping residents understand the process successfully."],
      },
             {
        layout: "full",
        src: "Image/Project_9/05_DH_Proj9.png",
        title: "Design Improvement Plan",
        text: ["The design improvement strategy examines the balance between maintained units and saleable area, identifying opportunities to reorganize the residential program without sacrificing overall yield. Through iterative design testing, unit configurations are refined to maximize saleable keys while preserving the quality, exclusivity, and lifestyle amenities that define Ramhan Island's luxury offering."],
      },
      // {
      // layout: "duo",    
      //   srcs: [
      //     "Image/Project_6/08_DH_Proj6.png",
      //     "Image/Project_6/04_DH_Proj6.png",
      //   ],
      //   title: "Dayak Cosmology and the Meaning of Nature",
      //   text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      // },
    // {
    //     layout: "full",
    //     src: "Image/Project_6/10_DH_Proj6.png",
    //     // title: "Full Width View",
    //     // text: ["Description that sits below the full-width image."],
    //   },
      {
        layout: "full",
        src: "Image/Project_9/10_DH_Proj9.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
    ],
  },
];