const projects = [
  {
    id: "01",
    title: "When Forests Become Frontiers",
    italicWord: "Frontiers",
    tags: ["Research", "Environmental Justice", "Borneo", "Public Empowerment"],
    desc: "Six-part drawing series examining meranti extraction in West Borneo and its impact on Dayak communities.",
    long: "In Sabar Bubu, West Borneo, the forest’s rhythms are increasingly shaped by chainsaws and transport trucks as global demand for exotic hardwoods such as mahogany, teak, and meranti drives intensified extractivism. Expanding state forestry concessions overlap with Indigenous customary territories, accelerating deforestation, degrading biodiversity, and generating persistent disputes over land and authority. Meranti, prized for its strength and durability, is harvested at rates that exceed the forest’s regenerative capacity. For Dayak communities, meranti is more than a commodity. It defines adat boundaries, supports spiritual practices, and embodies ecological memory. Its disappearance represents not only environmental loss but also cultural erosion, as anchors of collective life and belonging vanish with the canopy. Drawing on Anna Tsing’s concept of friction as unequal and unstable encounters, this research frames these conflicts as sites where global markets and state forestry regimes unsettle Indigenous worlds and reshape the politics of land, legality, and identity.",
    year: "2025",
    medium: "Drawing / Research",
    image: "Image/Project_1/07_DH_Proj1.png",
    video: "https://www.youtube.com/embed/kDRsn2oVqQE?autoplay=1&mute=1",
    location: "West Borneo",
    status: "Completed",
    color: "linear-gradient(135deg, #3d4e1f 0%, #2c3816 100%)",
    images: [
      { src: "Image/Project_1/01_DH_Proj1.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_1/02_DH_Proj1.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: true,
        layout: "single"
      },
      {
        layout: "duo",    
        srcs: [
          "Image/Project_1/03_DH_Proj1.png",
          "Image/Project_1/04_DH_Proj1.png",
        ],
        title: "Dayak Cosmology and the Meaning of Nature",
        text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      },
      // { src: "Image/Project_1/05_DH_Proj1.png", 
      //   title: "Illicit Process During Extraction",
      //   text: "Extraction in West Borneo brings social and material devastation beyond forest loss. Dayak families face eviction, burned homes, destroyed tools, and illegal logging practices that evade detection. As exploitation deepens, communities turn to prayer and ritual, drawing spiritual resilience to endure and resist forces greater than their political and economic power.",  
      //   reverse: false,
      //   layout: "single"
      // },
      {
        layout: "full",
        src: "Image/Project_1/05_DH_Proj1.png", 
        title: "Illicit Process During Extraction",
        text: "Extraction in West Borneo brings social and material devastation beyond forest loss. Dayak families face eviction, burned homes, destroyed tools, and illegal logging practices that evade detection. As exploitation deepens, communities turn to prayer and ritual, drawing spiritual resilience to endure and resist forces greater than their political and economic power.",
      },
      { src: "Image/Project_1/06_DH_Proj1.png", 
        title: "Vicious Cycle",
        text: "Forest conflict in West Borneo exposes a political and economic cycle that weakens Indigenous land rights. Overlapping laws, poor enforcement, and corruption enable state institutions and corporations to benefit from extraction. Through elite networks and permits, concessions expand despite objections, leaving Dayak communities with rights recognized legally but undermined in practice." ,  
        reverse: false,
        layout: "single"
      },

    ],

  },
  {
    id: "02",
    title: "South Bronx Pedestrian Atlas",
    italicWord: "Atlas",
    tags: ["Web Mapping", "Mapbox GL JS", "C#", "JavaScript","Digital Commisioning"],
    desc: "Interactive web application visualizing pedestrian density, traffic flows, and PLOS across the South Bronx.",
    long: "This proposal advances an integrated strategy to transform South Bronx streets into safer, more inclusive, and community oriented public spaces by rebalancing movement and place. Although many corridors experience high pedestrian volumes, they continue to function primarily as vehicular thoroughfares, creating unsafe and stressful walking environments. Through traffic counts, pedestrian flow mapping, and density analysis, the strategy identifies redundant travel lanes and underutilized right of way that can be reallocated to widen sidewalks, enhance crossings, and introduce flexible public space. Corridors with excess vehicular capacity are prioritized for activation through the Open Streets program, incorporating modular and movable furniture to accommodate daily activities, local markets, and community gatherings. Mobility systems are reorganized through time based freight management, designated loading zones, and integrated bicycle, micromobility, and transit infrastructure. Together, these interventions reduce conflicts, improve circulation efficiency, and support a more equitable and people centered street environment.",
    year: "2025",
    medium: "Web Application",
    image: "Image/Project_2/01_DH_WebApp.png",
    // video: "https://www.youtube.com/embed/kDRsn2oVqQE",
    location: "South Bronx, NY",
    status: "Completed",
    color: "linear-gradient(135deg, #4a5e28 0%, #3d4e1f 100%)",
    images: [
      { src: "Image/Project_1/01_DH_4.228.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_1/02_DH_4.228.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: true,
        layout: "single"
      },
    ],
  },
  {
    id: "03",
    title: "OrangoPlan — Grasshopper Plugin",
    italicWord: "Plugin",
    tags: ["C#", "Python","Grasshopper SDK","Digital Commisioning"],
    desc: "Grasshopper plug enabling real-time urban design and planning prototyping.",
    long: "OrangoPlan provides parametric tools to model, analyze, and visualize complex urban design workflows. It enables designers and planners to create adaptive street networks, land-use layouts, building massing, public space configurations, and infrastructure simulations.",
    year: "2024 - Ongoing",
    medium: "Software / Plugin",
    image: "Image/Project_3/01_DH_Logo.png",
    video: "https://www.youtube.com/embed/K9SeA-3_E0w?autoplay=1&mute=1",
    location: "MIT SA+P",
    status: "Ongoing",
    color: "radial-gradient(ellipse at top left, #566830 0%, #2c3816 100%)",
    images: [
      { src: "Image/Project_1/01_DH_4.228.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_1/02_DH_4.228.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: true,
        layout: "single"
      },


    ],
  },
  {
    id: "04",
    title: "Smoked County Relish",
    italicWord: "Relish",
    tags: [ "Thesis", "C#","Java Script","Python","Building Science","Discrete Math"],
    desc: "Rethinking coastal culture to revoke poverty and technological disjunction in Indonesia",
    long: "Indonesia, as a country consisting of islands, holds an affinity for coastal cultures. Evolve within absolute time; the indigenous support their lives by gaining the source and preserving it with various methods. Semarang City, located on northern Java Island, is famous for its smoked fish preservation. As they believe the technique is sea frontliners inheritance, they are stigmatized as second-class people. The design effort seeks appropriateness and reuse of heritage buildings to secure the perimeter and encourage community resilience. In tourism attraction strategy, they must race during environmental degradation.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_4/01_DH_Proj4.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns?autoplay=1&mute=1",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_4/11_DH_Proj4.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_4/12_DH_Proj4.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: true,
        layout: "single"
      },
      { src: "Image/Project_4/03_DH_Proj4.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_4/09_DH_Proj4.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_4/08_DH_Proj4.gif",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      { src: "Image/Project_4/06_DH_Proj4.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_4/10_DH_Proj4.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      // {
      // layout: "duo",    
      //   srcs: [
      //     "Image/Project_4/05_DH_Proj4.png",
      //     "Image/Project_4/04_DH_Proj4.png",
      //   ],
      //   title: "Dayak Cosmology and the Meaning of Nature",
      //   text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      // },
      { src: "Image/Project_4/07_DH_Proj4.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: false,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_4/01_DH_Proj4.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },

    ],
  },
  {
    id: "05",
    title: "Jakarta TOD-POD Implementation",
    italicWord: "Implementation",
    tags: ["Research",,"C#", "Python", "Urban Mobility", "Public Empowerment"],
    desc: "Creating a TOD-POD template to better shape urban mobility within the Jakarta Metropolitan Area.",
    long: "The Jakarta metropolitan area (Jabodetabek) consists of Jakarta, Bogor, Depok, Tangerang, and Bekasi, covering over 6,438 sq km, and it is considered the second largest metropolitan area in the world after the Tokyo metropolitan area in Japan (14,034 sq km). The metropolitan area is home to a population of 40 million people in 2022.There has been relatively little focus on the ‘implementation’ of strategic imperatives, with most urban development and transit initiatives emerging through either reactive or speculative means. Therefore, the city’s planning administration needs to strengthen its understanding and knowledge in planning Transit-Oriented Development (TOD) and Pedestrian-Oriented Design (POD).",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_5/01_DH_TOD.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_7/01_DH_Proj7.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_4/03_DH_Proj4.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: true,
        layout: "single"
      },
      { src: "Image/Project_4/09_DH_Proj4.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: false,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_4/08_DH_Proj4.gif",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      { src: "Image/Project_4/06_DH_Proj4.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: true,
        layout: "single"
      },
    ],
  },
  {
    id: "07",
    title: "Indonesia New Capital City Urban Design Guidelines",
    italicWord: "Guidelines",
    tags: ["Research", "C#", "Python", "Planning Modelling"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_7/07_DH_Proj7.png",
    // video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Nusantara, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_7/03_DH_Proj7.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_7/09_DH_Proj7.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_7/08_DH_Proj7.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
                        {
        layout: "full",
        src: "Image/Project_7/02_DH_Proj7.gif",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      // {
      // layout: "duo",    
      //   srcs: [
      //     "Image/Project_4/05_DH_Proj4.png",
      //     "Image/Project_4/04_DH_Proj4.png",
      //   ],
      //   title: "Dayak Cosmology and the Meaning of Nature",
      //   text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      // },
      { src: "Image/Project_7/05_DH_Proj7.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: false,
        layout: "single"
      },
                  {
        layout: "full",
        src: "Image/Project_7/04_DH_Proj7.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      { src: "Image/Project_7/10_DH_Proj7.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: true,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_7/06_DH_Proj7.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      {
        layout: "full",
        src: "Image/Project_7/01_DH_Proj7.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },


    ],
  },
  {
    id: "06",
    title: "Reclaiming Necessity Coastal Demak",
    italicWord: "Coastal Demak",
    tags: ["p5.js", "Arduino", "Interactive"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_6/01_DH_Proj6.png",
    // video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [
      { src: "Image/Project_6/02_DH_Proj6.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: false,
        layout: "single"
      },
      {
        layout: "full",
        src: "Image/Project_6/05_DH_Proj6.png",
      },
      { src: "Image/Project_6/09_DH_Proj6.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: true,
        layout: "single"
      },
      { src: "Image/Project_6/03_DH_Proj6.png", 
        title: "Disputed Extraction Site",
        text: "For centuries, Dayak communities governed land through adat systems. Although the 1960 Agrarian Law recognized customary rights, weak enforcement enabled state backed concessions. In Sabar Bubu, severe deforestation and forced displacement followed, affecting thousands. The case exposes how legal ambiguity and extraction undermine Indigenous territory and belonging." ,  
        reverse: false,
        layout: "single"
      },
      { src: "Image/Project_6/06_DH_Proj6.png", 
        title: "Demand History of Exotic Wood – Meranti",
        text: "Global demand for meranti grew in the nineteenth century, driving trade oriented logging in Southeast Asia. By the late twentieth century, corporate expansion in Borneo sharply increased deforestation. Under Suharto, concessions favored elites, accelerating extraction. Decentralization later intensified conflicts, while global construction and furniture markets continue sustaining ecological and social pressures.",   
        reverse: true,
        layout: "single"
      },
      // {
      // layout: "duo",    
      //   srcs: [
      //     "Image/Project_6/08_DH_Proj6.png",
      //     "Image/Project_6/04_DH_Proj6.png",
      //   ],
      //   title: "Dayak Cosmology and the Meaning of Nature",
      //   text: ["Dayak cosmology unites land, spirits, and humans within interconnected cosmic realms. The sacred meranti tree links physical and ancestral worlds and is used only for essential needs. Through ritual sacrifice and liver divination, territorial decisions align with cosmic balance, making forest defense both political resistance and sacred obligation."],
      // },
    {
        layout: "full",
        src: "Image/Project_6/10_DH_Proj6.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
      {
        layout: "full",
        src: "Image/Project_6/07_DH_Proj6.png",
        // title: "Full Width View",
        // text: ["Description that sits below the full-width image."],
      },
    ],
  },

  {
    id: "08",
    title: "Experimenting Gentle Density of  Tanah Abang TOD",
    italicWord: "TOD",
    tags: ["p5.js", "Arduino", "Interactive"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_8/01_DH_Density.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [],
  },
  {
    id: "09",
    title: "Middle East Strategic",
    italicWord: "Strategic",
    tags: ["p5.js", "Arduino", "Interactive"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_9/01_DH_MiddleEast.png",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [],
  },
];