const projects = [
  {
    id: "01",
    title: "When Forests Become Frontiers",
    italicWord: "Frontiers",
    tags: ["Drawing", "Environmental Justice", "Borneo", "Public Empowerment"],
    desc: "Six-part drawing series examining meranti extraction in West Borneo and its impact on Dayak communities.",
    long: "The rhythms of the forest of Sabar Bubu in West Borneo reverberate with chainsaws and transport trucks. Global demand for exotic hardwoods, including mahogany, teak, and meranti, has intensified destructive extractivism. As concessions expand and land is cleared, deforestation accelerates, biodiversity declines, and Indigenous territorial life becomes increasingly destabilized. Overlaps between state forestry concessions and customary territories have produced persistent disputes, turning the forest into a contested terrain of claims and authority. Meranti, valued for its strength and durability, has become a high demand commodity pushing harvest cycles far beyond what the forest can replenish. For Dayak communities, the original inhabitants of these forests, meranti is not merely timber. It marks customary (adat) boundaries, guides spiritual practices, and sustains ecological memory. When meranti trees disappear, the loss is both environmental and cultural. A canopy vanishes, and with it, anchors of life. This research plots these conflicts as sites of friction, described by Anna Tsing as awkward, unequal, unstable encounters, revealing how global extraction and state forestry regimes unsettle Indigenous worlds and reconfigure the politics of land, legality, and belonging.",
    year: "2025",
    medium: "Drawing / Research",
    image: "Image/Project_1/07_DH_4.228.png",
    video: "https://www.youtube.com/embed/kDRsn2oVqQE",
    location: "West Borneo",
    status: "Completed",
    color: "linear-gradient(135deg, #3d4e1f 0%, #2c3816 100%)",
    images: [
      { src: "Image/Project_1/01_DH_4.228.png", 
        title: "Aerial Territory Mapping",
        text: "Concession boundaries overlaid on forest cover loss data, tracing the corporate transformation of ancestral land.",   
        reverse: false    
      },
      { src: "Image/Project_1/02_DH_4.228.png", 
        title: "Aerial Territory Mapping",
        text: "Concession boundaries overlaid on forest cover loss data, tracing the corporate transformation of ancestral land." ,  
        reverse: true
      },
      { src: "Image/Project_1/01_DH_4.228.png", 
        title: "Aerial Territory Mapping",
        text: "Concession boundaries overlaid on forest cover loss data, tracing the corporate transformation of ancestral land.",   
        reverse: false    
      },
    ],
    imageCaption: {
      title: "Seeding the Wetlands. Growing the Community",
      text: "The Lower Ninth Ward's history has been largely entwined with the Bayou Bienvenue which borders north of the neighbourhood. This dense cypress swamp has been in decline since the mid-1900s..."
      
    },
  },
  {
    id: "02",
    title: "South Bronx Pedestrian Atlas",
    italicWord: "Atlas",
    tags: ["Web Mapping", "Mapbox GL JS", "C#", "JavaScript","Digital Commisioning"],
    desc: "Interactive web application visualizing pedestrian density, traffic flows, and PLOS across the South Bronx.",
    long: "Built with Mapbox GL JS and custom vector tilesets, this atlas overlays pedestrian volume counts, Level of Service grades, and real-time traffic data onto a live street map.",
    year: "2025",
    medium: "Web Application",
    image: "Image/Project_2/01_DH_WebApp.png",
    video: "https://www.youtube.com/embed/kDRsn2oVqQE",
    location: "South Bronx, NY",
    status: "Completed",
    color: "linear-gradient(135deg, #4a5e28 0%, #3d4e1f 100%)",
    images: [], 
  },
  {
    id: "03",
    title: "OrangoPlan — Grasshopper Plugin",
    italicWord: "Plugin",
    tags: ["C#", "Python","Grasshopper SDK","Digital Commisioning"],
    desc: "Grasshopper plug enabling real-time urban design and planning prototyping.",
    long: "OrangoPlan provides parametric tools to model, analyze, and visualize complex urban design workflows. It enables designers and planners to create adaptive street networks, land-use layouts, building massing, public space configurations, and infrastructure simulations.",
    year: "2024 - Ongoing",
    medium: "Software / Plugin",
    image: "Image/Project_3/01_DH_Logo.png",
    video: "https://www.youtube.com/embed/K9SeA-3_E0w",
    location: "MIT SA+P",
    status: "Ongoing",
    color: "radial-gradient(ellipse at top left, #566830 0%, #2c3816 100%)",
    images: [],
  },
  {
    id: "04",
    title: "Smoked County Relish",
    italicWord: "Relish",
    tags: ["Thesis", "Material Culture", "C#", "Building Science","Salty Urbanism"],
    desc: "Rethinking coastal culture to revoke poverty and technological disjunction in Indonesia",
    long: "Indonesia, as a country consisting of islands, holds an affinity for coastal cultures. Evolve within absolute time; the indigenous support their lives by gaining the source and preserving it with various methods. Semarang City, located on northern Java Island, is famous for its smoked fish preservation. As they believe the technique is sea frontliners inheritance, they are stigmatized as second-class people. The design effort seeks appropriateness and reuse of heritage buildings to secure the perimeter and encourage community resilience. In tourism attraction strategy, they must race during environmental degradation.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_4/01_DH_Display.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [],
  },
  {
    id: "05",
    title: "Jakarta TOD-POD Implementation",
    italicWord: "Implementation",
    tags: ["Research", "Computational Design","C#", "Python", "Urban Mobility", "Public Empowerment"],
    desc: "Creating a TOD-POD template to better shape urban mobility within the Jakarta Metropolitan Area.",
    long: "The Jakarta metropolitan area (Jabodetabek) consists of Jakarta, Bogor, Depok, Tangerang, and Bekasi, covering over 6,438 sq km, and it is considered the second largest metropolitan area in the world after the Tokyo metropolitan area in Japan (14,034 sq km). The metropolitan area is home to a population of 40 million people in 2022.There has been relatively little focus on the ‘implementation’ of strategic imperatives, with most urban development and transit initiatives emerging through either reactive or speculative means. Therefore, the city’s planning administration needs to strengthen its understanding and knowledge in planning Transit-Oriented Development (TOD) and Pedestrian-Oriented Design (POD).",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_5/01_DH_TOD.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [],
  },
    {
    id: "06",
    title: "Reclaiming Necessity Coastal Demak",
    italicWord: "Coastal Demak",
    tags: ["p5.js", "Arduino", "Interactive"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_6/01_DH_Diag.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [],
  },
  {
    id: "07",
    title: "Indonesia New Capital City Urban Design Guidelines",
    italicWord: "Guidelines",
    tags: ["p5.js", "Arduino", "Interactive"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_7/01_DH_IKN.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [],
  },
  {
    id: "08",
    title: "Experimenting Gentle Density of  Tanah Abang TOD",
    italicWord: "TOD",
    tags: ["p5.js", "Arduino", "Interactive"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_8/01_DH_Density.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [],
  },
  {
    id: "09",
    title: "Middle East Strategic",
    italicWord: "Strategic",
    tags: ["p5.js", "Arduino", "Interactive"],
    desc: "Hardware-integrated tap-beat game with Arduino button inputs and PoseNet nose-tracking for gameplay control.",
    long: "A physically embodied rhythm game that merges web audio, ml5.js PoseNet body tracking, and real Arduino buttons for tactile feedback.",
    year: "2021",
    medium: "Computational Design",
    image: "Image/Project_9/01_DH_MiddleEast.png",
    video: "https://www.youtube.com/embed/QVvZqij31Ns",
    location: "Soegijapranata Catholic University",
    location: "Semarang, Indonesia",
    status: "Completed",
    color: "linear-gradient(160deg, #3d4e1f 0%, #5a7225 100%)",
    images: [],
  },
];